services:
  web:
    image: php:8.2-apache #check the php version you need for your project
    ports:
      - "8000:80" #this line maps your pc port to the container port
    depends_on:
      - db #this line links this container to the db container
    volumes:
      - ./public:/var/www/html #this line maps the content of ./html in your pc to the /var/www/html of the container
      - ./app:/var/www/app #this line maps the content of ./html in your pc to the /var/www/html of the container
    environment:
      - PHP_EXTENSION=mysqli,pdo,pdo_mysql
    command: >
      bash -c "
        a2enmod rewrite &&
        docker-php-ext-install pdo pdo_mysql && 
        apache2-foreground
      "

  db:
    image: mysql:8.1.0 #check the mysql version you need for your project
    environment:
      MYSQL_ROOT_PASSWORD: mior #you can change the mysql root password here
      MYSQL_DATABASE: answerdb #you can change the database name here
    volumes:
      - ./mysql_data:/var/lib/mysql #this line maps the content of ./mysql_data in your pc to the /var/lib/mysql of the container
      - ./init-sql:/docker-entrypoint-initdb.d # ✅ Add this to execute SQL on startup

#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    ports:
#      - "8080:80" #this line maps your pc port to the container port
#    depends_on:
#      - db #this line links this container to the db container
#    environment:
#      PMA_HOST: db
